services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Wexample\SymfonyUserDs\Controller\:
        resource: '../../Controller/'
        tags: ['controller.service_arguments']

    Wexample\SymfonyUserDs\Twig\:
        resource: '../../Twig/'

    Wexample\SymfonyUserDs\DevMenu\:
        resource: '../../DevMenu/'
